
# constants for the feature extraction

INCLUDE_MAJOR_AXIS_LENGTH = True
INCLUDE_AXIS_RATIO = True
INCLUDE_EXTENT = True
INCLUDE_AREA = True
INCLUDE_PERIMETER = True
INCLUDE_CONVEX_AREA = True
INCLUDE_SOLIDITY = True
INCLUDE_ECCENTRICITY = True
INCLUDE_MEAN_INTENSITY = True
INCLUDE_MAX_INTENSITY = True
INCLUDE_MIN_INTENSITY = True

INCLUDE_NEIGHBORHOOD = True
INCLUDE_INTENSITY = True
INCLUDE_ZERNIKE = True
INCLUDE_HU = True

INCLUDE_HOG = False