
# constants for the feature extraction


INCLUDE_NEIGHBORHOOD = False
INCLUDE_INTENSITY = False
INCLUDE_ZERNIKE = True
INCLUDE_HOG = False
INCLUDE_HU = True

INCLUDE_MAJOR_AXIS_LENGTH = True
INCLUDE_AXIS_RATIO = True
INCLUDE_EXTENT = True
INCLUDE_AREA = False
INCLUDE_PERIMETER = False
INCLUDE_CONVEX_AREA = False
INCLUDE_SOLIDITY = False
INCLUDE_ECCENTRICITY = False
INCLUDE_MEAN_INTENSITY = False
INCLUDE_MAX_INTENSITY = False
INCLUDE_MIN_INTENSITY = False


